---

- name: Install nginx
  apt: pkg=nginx state=installed update_cache=true

 # - name: Creates SSL directory
 #   file: path=/etc/nginx/ssl state=directory

 # - name: Copy ssl certificate
 #  copy: src=server.crt dest=/etc/nginx/ssl/{{server_hostname}}.crt

 #  - name: Copy ssl key
 #    copy: src=server.key dest=/etc/nginx/ssl/{{server_hostname}}.key

- name: Copy nginx configuration
  template: src=default dest=/etc/nginx/sites-available/default
  notify: restart nginx
